### ISSUE TITLE
Fix indentation

### ISSUE THREAD

**Issue by gouravkhunger** [genicsblog/genics-bot#3]
Indentation is not consistent throughout the project. Would love to see a PR fixing that :)

**Comment by gouravkhunger** [comment]
Also, remove the extra `;` that crept into the project. Most files don't have them but replace them where they are.

**Comment by bpires** [comment]
Hey @gouravkhunger, just pointing out that this PR should be manually closed. Because you didn't put the keyword `fix` right before the issue number, GitHub didn't catch it :) Happy HacktoberFest!

**Comment by gouravkhunger** [comment]
Yeah @bpires! I didn't close this issue because not all files were fixed in that commit. For example, [`log-analytics.js`](https://github.com/genicsblog/genics-bot/blob/main/util/log-analytics.js) & [`pending-review.js`](https://github.com/genicsblog/genics-bot/blob/main/util/pending-review.js) have different formatting.

It would be better to use a consistent 2 space tab for formatting all the files in the project. Probably need to setup vs code settings to fix things automatically.

Would you like to take up this issue? But I fear reviewers at hacktoberfest might consider PRs for this issue as spam because it's just whitespace mess.

**Comment by bpires** [comment]
Oh, I see! I could give it a try with VS Code settings :)

Don't worry about HacktoberFest, I'm way pass my PRs, just want to keep rolling and contributing 🎉

**Comment by gouravkhunger** [comment]
awesome! I will mark the PR with label "invalid" then so that hacktoberfest reviewers don't mark your PR as spam as that might count as negative.

I checked the PR but still the indents were way too wide:

https://github.com/genicsblog/genics-bot/blob/0fc50ce2bfc978039a31ce895d8b8a18950d42c9/commands/ping.js#L1-L16

I figured that was my own mistake. I should have told "Indents with spaces" rather than "tab spaces", that was where the mismatch happened.

I have fixed that in a new commit in your PR itself:

https://github.com/genicsblog/genics-bot/blob/b861540344c4fcaa46da44aea168b015fac6f543/commands/ping.js#L1-L16

It's good to go now!

**Comment by bpires** [comment]
Yeah, sorry for that, I thought you wanted to use tab spaces indeed haha just a miscommunication, but I'm glad that it worked out, and I've learned how to set up VS Code for correct indentation! That's a win-win, cheers @gouravkhunger! Keep up the good work.

**Comment by gouravkhunger** [comment]
thanks & same to you!
